### ISSUE TITLE
Make style between first page and second page consistent

### ISSUE THREAD

**Issue by anlijuncn** [priyamDalmia/priyamDalmia.github.io#2]
Hi Priyam, 

Thanks for your beautiful template, I have used it for my personal Github Page as well. 

I have one question, Are there any parameters I could set to make the style between pages more consistent? It seems the first page has "higher floating"? 

I have attached the screenshot. 
![image](https://user-images.githubusercontent.com/38600288/185786369-d23664fc-bd6e-4927-ad24-603464ebca1e.png)

**Comment by priyamDalmia** [comment]
Hi An,

I believe those are just the shadows around the box. There are style
elements for box shadows in the CSS file. You can modify them to get a more
consistent border.

Feel free to reach out if you have any questions.

Kind Regards,
Priyam Dalmia

**Comment by anlijuncn** [comment]
Thanks, I have found it to modify
